title: Yunpu Zeng

logo: /IMG_1337.JPG

description: >
  Ph.D. Student in Industrial Engineering<br>
  Georgia Institute of Technology<br><br>
  Healthcare Operations<br>
  Disease Modeling<br>
  Microsimulation<br><br>
  <a href="https://github.com/Yunpuzeng">GitHub</a> ·
  <a href="https://orcid.org/0009-0004-7652-3358">ORCID</a> ·
  <a href="https://www.linkedin.com/in/yunpu-zeng-49568728a">LinkedIn</a>

show_downloads: false

theme: jekyll-theme-minimal
